MiniTetris
BaseWebDev/HT_6 pull request #1
Opened 2018-04-21 22:31 UTC by SermusAnton

2018-04-24 19:07 UTC, ilpoli requested changes

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Canvas.cs
> +        public Canvas(int x, int y, int w, int h, ConsoleColor col) : base(x, y, w, h) {
Этот конструктор не используется.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/FactoryFigure.cs
> +        public FactoryFigure(int x, int y, ConsoleColor color) : base(x, y) {
Не используется.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/FactoryFigure.cs
> +            switch (TypeFigure) {
лучше каждый case разбить не отдельные методы, метод будет меньше и проще читаться, каждый метод будет иметь имя которое отражает фигуру.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/FactoryFigure.cs
> +        }
помнишь, перегрузка должна дополнять, а не изменять. это значит что base по хорошему должен вызываться. если это не твой случай, проверь что выбран правильный объект для наследования.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Figure.cs
> +        public Figure(int x, int y, int turn):base(x,y) {
полагаю что один из конструкторов тоже лишний )

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Heap.cs
> +            return point.Y == DeleteLine;
можно добавить свойство visible и его ставить, если false то не вызывать у фигуры метод draw, в таком случае можно значительно улучшить производительность.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Point.cs
> +                return this.Y- temp.Y;
Point temp = obj as Point;
if(temp!=null) {
return this.Y- temp.Y;
}

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Render.cs
> +            foreach (var line in deleteLines) { // Делаем так чтоб не использовать IEnumerable<Point> вызывает ошибку
вызывает потому что ты меняешь коллекцию, решить просто heap.ToList(), тогда foreach Будет идти по другой коллекции и это не вызовет ошибки никакой.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Render.cs
> +                                figure.CountTurn++;
отдельным методом лучше.

2018-04-24 19:07 UTC, ilpoli commented on SimpleInterface/Render.cs
> +                                RightMove(figure);
лучше конечно сделать фигуру которую можно двигать, и вызывать figure.Right() или Left и т.д. а то у тебя render очень много делает.

2018-05-09 22:03 UTC, SermusAnton commented
Исправил

2018-06-06 11:08 UTC, ilpoli approved these changes

2018-06-06 13:51 UTC, merged